version: '3.8'
services:
  mongo_db:
    image: mongo:7.0-jammy
    ports: 
      - "27010:27017"

    container_name: mongodb-for-tests
    volumes:
      - /data/db

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}

  fastapi:
    build: ./FastAPI
    ports:
      - 8001:8000
    container_name: fastapi-for-tests
    environment:
      - CONNECTION_TO_MONGODB=${CONNECTION_TO_MONGODB}
    depends_on:
      - mongo_db